export const T = {
  cream: "#fce8d8",
  paper: "#ffffff",
  pinkSoft: "#fbd3da",
  pinkLight: "#f9c0d0",
  pink: "#ec5b9b",
  pinkHot: "#ee3a83",
  pinkDeep: "#d83b85",
  mint: "#b8dfd9",
  sky: "#b0dde7",
  peach: "#f7ab93",
  peachSoft: "#fbc7a8",
  yellow: "#f8d471",
  lilac: "#d6bbe0",
  ink: "#3a2532",
  inkSoft: "rgba(58,37,50,0.75)",
  inkMute: "rgba(58,37,50,0.55)",
  script: "var(--font-allison), 'Dancing Script', cursive",
  display: "var(--font-luckiest-guy), 'Luckiest Guy', cursive",
  body: "var(--font-quicksand), 'Quicksand', system-ui, sans-serif",
};
